#!/bin/sh

set -e

UPSTREAM_NAME_API="backend_api"
UPSTREAM_NAME_SIGNALR="backend_signalr"
BACKEND_HOST="${BACKEND_HOST:-backend}"
BACKEND_PORT="${BACKEND_PORT:-8080}"
CONFIG_FILE="/etc/nginx/conf.d/default.conf"
RESOLVE_INTERVAL="${RESOLVE_INTERVAL:-10}"
SELF_CONTAINER_IP="$(hostname -i 2>/dev/null || echo '')"

log() {
    echo "[entrypoint] $(date -Iseconds) $*"
}

resolve_backend_ips() {
    nslookup "$BACKEND_HOST" 127.0.0.11 2>/dev/null \
        | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' \
        | grep -v '^127\.' \
        | grep -vF "${SELF_CONTAINER_IP}" \
        | sort -t. -k1,1n -k2,2n -k3,3n -k4,4n \
        | uniq \
        || true
}

gen_upstream() {
    name="$1"
    mode="$2"
    shift 2

    echo ""
    echo "upstream ${name} {"

    if [ "$mode" = "hash" ]; then
        echo "    hash \$cookie_signalr_id consistent;"
    fi

    for ip in "$@"; do
        echo "    server ${ip}:${BACKEND_PORT};"
    done

    echo "}"
    echo ""
}

generate_config() {
    all_ips="$1"

    # Write a heredoc with the full config
    cat > "$CONFIG_FILE" << EOF
# ---------------------------------------------------------------------------
# nginx load-balancer configuration for Real-Time Financial Monitor.
# AUTO-GENERATED by entrypoint.sh -- do not edit manually.
#
# Generated at: $(date -Iseconds)
# Backend replicas ($(echo "$all_ips" | wc -w)): ${all_ips}
# ---------------------------------------------------------------------------

upstream ${UPSTREAM_NAME_API} {
$(for ip in $all_ips; do echo "    server ${ip}:${BACKEND_PORT};"; done)
}

upstream ${UPSTREAM_NAME_SIGNALR} {
    hash \$cookie_signalr_id consistent;
$(for ip in $all_ips; do echo "    server ${ip}:${BACKEND_PORT};"; done)
}

server {
    listen 5000;
    server_name localhost;

    # ------------------------------------------------------------------
    # Load Balancer health check — returns 200 immediately, no backend.
    # ------------------------------------------------------------------
    location /lb-health {
        access_log off;
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }

    # ------------------------------------------------------------------
    # API routes — Round Robin across all backend replicas.
    # ------------------------------------------------------------------
    location /api/ {
        proxy_pass http://${UPSTREAM_NAME_API};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # ------------------------------------------------------------------
    # SignalR hub routes — STICKY via \$cookie_signalr_id consistent hash.
    #
    # This covers:
    #   POST /hubs/transactions/negotiate       → sticky (cookie exists)
    #   GET  /hubs/transactions?id=<token>      → sticky (cookie exists)
    #   WebSocket /hubs/transactions?id=<token> → sticky (cookie exists)
    #
    # The sticky-session cookie "signalr_id" is set by the SPA BEFORE
    # the SignalR connection is established, so it's present on the very
    # first /negotiate POST.
    # ------------------------------------------------------------------
    location /hubs/ {
        proxy_pass http://${UPSTREAM_NAME_SIGNALR};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket support
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        # Long-polling / SSE timeouts
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # ------------------------------------------------------------------
    # Health check — forward to backend pool (Round Robin).
    # ------------------------------------------------------------------
    location /health {
        proxy_pass http://${UPSTREAM_NAME_API};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }

    # ------------------------------------------------------------------
    # Sticky-test endpoint — forward through the signalr upstream so we
    # can verify consistent-hash routing with a simple GET request.
    # Same as /health but goes through backend_signalr.
    # ------------------------------------------------------------------
    location /sticky-test {
        proxy_pass http://${UPSTREAM_NAME_SIGNALR};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }

    # ------------------------------------------------------------------
    # Load Balancer sticky-session diagnostic — via sticky pool.
    # ------------------------------------------------------------------
    location /lb-debug {
        proxy_pass http://${UPSTREAM_NAME_SIGNALR};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF
}

# ===========================================================================
# Main
# ===========================================================================

log "Starting dynamic backend resolver"
log "Backend host: ${BACKEND_HOST}:${BACKEND_PORT}"

# Initial resolution — retry until the IP set stabilises (same set twice in a row)
# or until we hit the max retries.  Docker DNS may not have registered all replicas
# the very first time we query, so we keep trying until convergence.
ips=""
prev_ips=""
retries=0
max_retries=30
stable_count=0
while [ "$stable_count" -lt 2 ] && [ "$retries" -lt "$max_retries" ]; do
    ips="$(resolve_backend_ips | tr '\n' ' ' | sed 's/ *$//')"
    if [ -z "$ips" ] && [ -z "$prev_ips" ]; then
        retries=$((retries + 1))
        log "No backend IPs found yet (attempt ${retries}/${max_retries}), retrying in 2s..."
        sleep 2
        continue
    fi

    if [ "$ips" = "$prev_ips" ] && [ -n "$ips" ]; then
        stable_count=$((stable_count + 1))
        count="$(echo "$ips" | wc -w)"
        log "Backend IPs stable (${count} IP(s): ${ips}) — convergence ${stable_count}/2"
        if [ "$stable_count" -lt 2 ]; then
            sleep 1
        fi
    else
        stable_count=0
        if [ -n "$ips" ]; then
            count="$(echo "$ips" | wc -w)"
            log "Backend IPs changed (${count} IP(s): ${ips}), retrying..."
        fi
        prev_ips="$ips"
        sleep 1
    fi
    retries=$((retries + 1))
done

if [ -z "$ips" ]; then
    log "ERROR: No backend IPs found after ${max_retries} attempts."
    log "Starting with fallback — all requests will 502 until backends are available."
    ips="127.0.0.1"
fi

count="$(echo "$ips" | wc -w)"
log "Discovered ${count} backend IP(s): ${ips}"

log "Generating nginx configuration..."
generate_config "$ips"
log "Configuration written to ${CONFIG_FILE}"

# Show the generated config for debugging
log "--- Generated config ---"
cat "$CONFIG_FILE"
log "--- End config ---"

# Start the backend watcher in the background
watch_for_changes() {
    log "Starting backend watcher (interval: ${RESOLVE_INTERVAL}s)"
    prev_ips="$1"
    while true; do
        sleep "$RESOLVE_INTERVAL"
        current_ips="$(resolve_backend_ips | tr '\n' ' ' | sed 's/ *$//')"
        if [ -n "$current_ips" ] && [ "$current_ips" != "$prev_ips" ]; then
            log "Backend IPs changed: '${prev_ips}' -> '${current_ips}'"
            log "Regenerating config and reloading nginx..."
            generate_config "$current_ips"
            nginx -s reload
            log "nginx reloaded successfully"
            prev_ips="$current_ips"
        fi
    done
}

watch_for_changes "$ips" &
WATCHER_PID=$!
log "Backend watcher started (PID: ${WATCHER_PID})"

# Start nginx in the foreground
log "Starting nginx..."
exec nginx -g "daemon off;"
